// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRl7XAE8ifMV8ami0IauivbzXEqCNIWy8',
    appId: '1:34002504015:web:4f3f518f3039047db1dd3a',
    messagingSenderId: '34002504015',
    projectId: 'blooddonation-7dd00',
    authDomain: 'blooddonation-7dd00.firebaseapp.com',
    storageBucket: 'blooddonation-7dd00.appspot.com',
    measurementId: 'G-Z5RQK0G674',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAXMrevUsGqAAdbixx7mEB2264OeEZonU',
    appId: '1:34002504015:android:f647fe712c3d7066b1dd3a',
    messagingSenderId: '34002504015',
    projectId: 'blooddonation-7dd00',
    storageBucket: 'blooddonation-7dd00.appspot.com',
  );
}
